### ISSUE TITLE
Empty attribute value should be valid

### ISSUE THREAD

**Issue by noqsi** [lepton-eda/lepton-eda#104]
Right now, attributes with empty values are not allowed. But an empty string is a perfectly valid string, and can be useful for back ends driving downstream flows for which blank input is valid.

**Comment by vzh** [comment]
I agree with this. Besides, such attributes could work as templates, e.g. in `spice` backends.

**Comment by graahnul-grom** [comment]
@noqsi @vzh Although I agree with this, too, doing so right now will cause interoperability problems with `geda-gaf`. Schematics created in lepton
cannot be processed by that suite (`gschem` attributes with empty values
will be treated just like text, `gnetlist` will fail).
What about postponing the discussion and reopening the issue after
some major release?

**Comment by vzh** [comment]
Nothing will prevent users to create attributes in backward compatible manner.

**Comment by graahnul-grom** [comment]
Yes, but one have to always keep it in mind while working on schematics.
Allowing an empty values for attributes seems to me as something akin to file format change.
