### ISSUE TITLE
'Text Entry...' dialog should respect 'text-size' option's value

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#110]
Now it uses a hard-coded value - 12 (in `system-gschemrc` `text-size`
is set to 10). Also, it was found that the font size
checking code in `g_rc_text_size()` also uses hard-coded values
instead of `MINIMUM_TEXT_SIZE` and `DEFAULT_TEXT_SIZE` macros.
That was [reported](https://bugs.launchpad.net/geda/+bug/1565803) almost a year ago, but there's still no feedback.
It seems that the fix is still relevant. What do you think?
If need be, I can submit updated patches or make a pull request.

**Comment by vzh** [comment]
@graahnul-grom Please make a PR.
