### ISSUE TITLE
Freestyle colors are displayed as 'Unknown'

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#112]
User-defined colors ('freestyle', 4 of them), when set to some valid
color value (not `#f`) are all displayed as `'Unknown'` in color selection
combo box. Maybe it's better to [give them](https://github.com/graahnul-grom/lepton-eda/commit/8ef9280eb2d78bf0c588ae257f37340238f596c5) some distinguishable names?

**Comment by vzh** [comment]
Please do.
