### ISSUE TITLE
Height of One Pixel TextView

### ISSUE THREAD

**Issue by ehennes775** [lepton-eda/lepton-eda#158]
Inside the multiattrib dialog box, the value textview has a height of one pixel. This issue was fixed in a commit and reintroduced in a later commit.

Original Fix:
42182f0ae6b16171329f00f32ff1857d38c1c33e

Reintroduction:
79d6da9e2dec05716570ae9b99ba65f5ddec5bbc

**Comment by vzh** [comment]
@ehennes775 Does resurrecting of the line with "height-request" fixes the dialog on your system? (I cannot just reproduce the issue on my computer...)

**Comment by ehennes775** [comment]
It should, and if you fix it, I will test it.

The height of the textview is defined by the scrollbar buttons. Since my system has popup scroll bar widgets, the height is one pixel.

I've experimented with letting the labels on the left define the height of the table row and setting the textview cell to GTK_FILL. So far, it does not match the size of the other widgets.

**Comment by vzh** [comment]
Edward, please review #159.

**Comment by vzh** [comment]
@ehennes775 OK, the fix is in the master branch now. Please report if it works for you.

**Comment by ehennes775** [comment]
The fix works.

**Comment by vzh** [comment]
Great, thanks!
