### ISSUE TITLE
Custom font for the log window

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#166]
IMHO, it's natural to use some kind of monospaced font
for the log window. Better yet, let the user decide:
introduce a configuration key for that.
It's [easy](https://github.com/graahnul-grom/lepton-eda/commit/c63175a7eccfff160d1fac2a0901866ae146304d), though I'm unsure about group/key naming:
```ini
[schematic.log]
log-window-font=Droid Sans Mono 11
```

**Comment by vzh** [comment]
What about using
> [schematic.log-window]
> font=SomeFont

WDYT?

**Comment by graahnul-grom** [comment]
Looks good.
#167
