### ISSUE TITLE
Freestyle colors should not be disabled by default

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#224]
Disabling that colors effectively prohibit their usage:
if users want to share schematic files, they also have to
share their color schemes, because otherwise some text
will be invisible to those with default setup.

**Comment by graahnul-grom** [comment]
Besides, I would add another 4-6 freestyle colors, since 4 IMHO
is not sufficient.  However, I doubt we can do it now (if it will be decided at all),
due to backward compatibility that we have to maintain in the upcoming release.

**Comment by vzh** [comment]
Though we can do it afterwards :-)
I'd use the same color notation as in Scheme files (colormaps) to change colors of arbitrary objects.

**Comment by graahnul-grom** [comment]
@vzh 
> I'd use the same color notation as in Scheme files (colormaps) to change colors of arbitrary objects.

Are you talking about using that notation in *.sym and *.sch files instead of numbers (i.e. changing the file format)?

**Comment by vzh** [comment]
> Are you talking about using that notation in *.sym and *.sch files instead of numbers (i.e. changing the file format)?

Yes, though we don't have to change the existing format. We could extend it transforming it into something new in time provided that we change its version (read, the header line).
