### ISSUE TITLE
Reorganize the main menu

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#225]
A. `File` menu:
  1. delete duplicated `Revert` (already in `Page` menu)

B. `Edit` menu:
  1. combine to one item: `Object Properties...`:
    - `Color...`
    - `Line Width & Type...`
    - `Fill Type...`
    - `Pin Type...`

C. `View` menu:
  1. rename: `Sidebar` => `Right Dock`
  2. rename: `Status` => `Bottom Dock`

D. `Page` menu:
  1. separate `Revert` from the other items
  2. rename: `Revert` => `Revert...`

E. `Hierarchy` menu:
  1. delete duplicated `Documentation...` (already in `Help` menu)

F. `Options` menu:
  1. delete obsolete `Text Size...` item
  2. rename/rearrange, for example:
    - `Snap Grid Spacing...` => `Options...`
    - [separator]
    - `Scale up Grid Spacing` => `Grid +`
    - `Scale down Grid Spacing` => `Grid -`
    - [separator]
	- `Cycle grid styles` => `Grid style: cycle Dots/Mesh/Off`
    - `Toggle Snap On/Off` => `Grid snap: cycle Grid/Resnap/Off`
    - [separator]
    - `Toggle Outline/Box` => `Feedback mode: Outline/Box`
    - `Toggle Net Rubberband` => `Net: Rubberband On/Off`
    - `Toggle Magnetic Net` => `Net: Magnetic On/Off`
    - [separator]
    - `Show Coords Window...` => `Coords Window`
    - `Show Log Window...` => `Log Window`

Comments:
- B.1: all that commands do exactly the same: show `Object` dialog
box (`x_widgets_show_object_properties()`).
- C.3: currently, there is no way to show `find text state` window
unless docking windows GUI is enabled. We need to add a new action,
e.g. `view-find-text-state`. **[done]**
- F.2: `Options` menu:

![2018_07_03 06 21 34](https://user-images.githubusercontent.com/26083750/42197153-25557b3a-7e8a-11e8-939b-71daaa97f8f1.png)

![2018_07_03 06 20 37](https://user-images.githubusercontent.com/26083750/42197161-2bfe1352-7e8a-11e8-8159-f13f9909e9d6.png)

Any suggestions are welcome.

**Comment by graahnul-grom** [comment]
If anyone wants to try the menu modified as proposed, here's the diff attached.

[system-gschemrc.diff.txt](https://github.com/lepton-eda/lepton-eda/files/2341191/system-gschemrc.diff.txt)

**Comment by vzh** [comment]
Several notes after your suggestions:

- Should we add `&object-properties` Scheme function and replace several `&edit-something` with it? WDYT?

- I'd like "Sidebar" better than "Right Dock" (and why could not it be left, for example?). However, I don't quite understand what could be used instead of "Status" then. Especially, when the user doesn't use embedded dialogs.

- Why have you thrown out &hierarchy-documentation?

- Why have you thrown out &options-text-size?

Otherwise, I'm pretty happy with your changes.

BTW, it's strange that `OL` is not displayed for the "Show log window..." menu entry.

**Comment by graahnul-grom** [comment]
* Yes, I think we should replace `edit-color`, `edit-linetype`, `edit-filltype` and `edit-pin-type` with new `object-properties` action.
* Frankly, I do like "Sidebar" name, too. But `Right Dock` and `Bottom Dock` names precisely describes what we have now: rigid docking widgets that cannot be configured in any way. And these menu items makes no sense when `use-docks` is set to `false`. Some time ago I proposed (on gitter) to split up `system-gschemrc` file: that way it would be easier to dynamically generate the main menu in, say,  `system-gschemrc-menu.scm` file (taking into account user configuration).

* > Why have you thrown out &hierarchy-documentation?

I see no relation between hierarchy and component documentation. And that item is already present in `Help` menu.

* > Why have you thrown out &options-text-size?

When the users see such an item in `Options` menu they might expect that it should somehow affect the global settings (like `text-size` in `gschemrc`). But instead it just opens `Edit Text` dialog (the same as `Edit->Edit Text...`).

`O L` key sequence is rebound to another action in my configuration.

**Comment by graahnul-grom** [comment]
Some further modifications:

* rearrange some items
* add/remove `...` where appropriate
* add more separators
* move `Edit->Invoke Macro` => `File->Invoke Macro...`
* move `Edit->Show/Hide Inv Text` => `Attributes->Show/Hide Hidden Text`
* rename `Component Documentation...` => `Find Component Documentation`

[system-gschemrc_2.diff.txt](https://github.com/lepton-eda/lepton-eda/files/2352326/system-gschemrc_2.diff.txt)

**Comment by graahnul-grom** [comment]
@vzh I'll add a PR, though it would be hard to split it up.

Updated menu:
  - system-gschemrc: [system-gschemrc.txt](https://github.com/lepton-eda/lepton-eda/files/2595634/system-gschemrc.txt)
  - diff: [system-gschemrc_3.diff.txt](https://github.com/lepton-eda/lepton-eda/files/2595637/system-gschemrc_3.diff.txt)
  - screenshots (left - old, right - new):

![1_menu_file_old_new](https://user-images.githubusercontent.com/26083750/48711362-25aaf380-ec1c-11e8-9211-c12c681c5e69.png)

![2_menu_edit_old_new](https://user-images.githubusercontent.com/26083750/48711369-2b083e00-ec1c-11e8-8234-38a7e119cffd.png)

![3_menu_view_old_new](https://user-images.githubusercontent.com/26083750/48711532-9520e300-ec1c-11e8-8dad-2e79ed169053.png)

![4_menu_page_old_new](https://user-images.githubusercontent.com/26083750/48711768-1d06ed00-ec1d-11e8-8724-1603d8e45089.png)

![5_menu_add_old_new](https://user-images.githubusercontent.com/26083750/48711887-6bb48700-ec1d-11e8-8e47-3f5074f07b8e.png)

![6_menu_hier_old_new](https://user-images.githubusercontent.com/26083750/48711979-ab7b6e80-ec1d-11e8-9b10-7dfa3e98d197.png)

![7_menu_attr_old_new](https://user-images.githubusercontent.com/26083750/48712174-2b093d80-ec1e-11e8-9a46-12995e906072.png)

![8_menu_options_old_new](https://user-images.githubusercontent.com/26083750/48712348-96eba600-ec1e-11e8-82b3-668e75009fe3.png)

![9_menu_help_old_new](https://user-images.githubusercontent.com/26083750/48712521-ff3a8780-ec1e-11e8-8629-a22ab4745988.png)

**Comment by vzh** [comment]
For some reason, #281 did not automatically close the issue, so I do it manually.
