### ISSUE TITLE
Trouble building developer docs

### ISSUE THREAD

**Issue by noqsi** [lepton-eda/lepton-eda#300]
I can't get the developer documentation to build for lepton-eda-1.9.7 on Ubuntu Xenial. LaTeX emits a thousand errors and finally gives up.

[untitled.txt](https://github.com/lepton-eda/lepton-eda/files/2692091/untitled.txt)

**Comment by graahnul-grom** [comment]
@noqsi Thank you for the report. I cannot generate the latex output on ubuntu (18.04, "bionic"), too. However, html output is fine. For a quick fix please try the attached patch.
What it does:
- disables generation of latex output files
- excludes `netlist` and `symcheck` subdirs: these tools were rewritten in `Scheme`; AFAIK doxygen doesn't support that language

[doxy_ubu1804.diff.txt](https://github.com/lepton-eda/lepton-eda/files/2694420/doxy_ubu1804.diff.txt)

To apply the patch:
- `cd` to `lepton-eda` source directory
- `git apply doxy_ubu1804.diff`

**Comment by noqsi** [comment]
This seems to work. Thanks.
