### ISSUE TITLE
Warnings about missing *.conf files should be disabled by default

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#382]
Even if there are no `geda.conf`, `geda-user.conf` or
`geda-system.conf` files, all tools behaves properly, because
the default values for all configuration parameters are used.
There is no point in reminding the end user every time about
these (missing) configuration files.
Since introduction of the `Netlist` menu in `lepton-schematic`,
these warnings start to appear in its log, too, bringing in even
more unnecessary confusion.

**Comment by vzh** [comment]
I agree with you here. There's no point to store many same config settings in several places. And our program is not a network service to choose many special settings for different situations. Besides, some (many?) large projects have great configure possibilities with robust defaults and little configuration files. Hope you'll make this Lepton side better, too :-)
