### ISSUE TITLE
Remove deprecated export functions and options

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#419]
Exporting with `scripts/image.scm` and `scripts/print.scm`
`lepton-schematic` scripts is deprecated since 2012 (git: 626a205).
We have enough tools to perform schematic export:
`File->Write Image...` dialog in `lepton-schematic`
and `lepton-cli export`.

The following should be deleted:
- `image-color` `gschemrc` option
- `image-size` `gschemrc` option (absent in `conf/schematic/options.scm`)
- `gschem-pdf` guile function (`g_funcs.c`)
- `gschem-image` guile function (`g_funcs.c`)
- `gschem-use-rc-values` guile function (`g_funcs.c`)
- `lepton-schematic`'s `--output` command line switch

Define `image-color` and `image-size` using `define-rc-dead-config`.
Define functions from `g_funcs.c` in the `(gschem deprecated)` module.
Make them do nothing, just print deprecation warning.

**Comment by vzh** [comment]
In my view, it'd be very nice if we still had guile functions for exporting pdf and images available for using in Scheme scripts.

**Comment by graahnul-grom** [comment]
Agree, it would be useful.
We could add such functions (later), e.g. something like `(schematic export)` module.
But current implementation is not satisfactory, and if you don't mind, I will remove it.
