### ISSUE TITLE
Log files should not be stored in the user's configuration directory

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#427]
Although we have log rotation implemented, log directory may contain
hundreds of files from all tools in the suite.
User's configuration directory (which may be under source control)
is not the right place for log files, they should go to some temporary location.
`$XDG_CACHE_HOME/lepton-eda/logs/` would be more appropriate.
We could also make it configurable.

**Comment by vzh** [comment]
Good catch, thanks!
