### ISSUE TITLE
Make sure localised strings have re-orderable substitutions where possible

### ISSUE THREAD

**Issue by gareth8118** [lepton-eda/lepton-eda#49]
Where strings are localised and have substitutions, those substitutions should have the *param-no* in the format string to allow translators to reorder the substitutions if it makes sense for that translation.

https://www.gnu.org/software/libc/manual/html_node/Output-Conversion-Syntax.html#Output-Conversion-Syntax 

It is probably worthwhile adding this *param-no* specifier even if there is only one substitution for the sake of consistency and to defend against forgetting to add it if a second substitution is added.

There is some justification in [Dwayne Bailey's FOSDEM 2016 talk](https://archive.fosdem.org/2016/schedule/event/10_easy_steps_to_ruin_your_localization/).

_copied in from the wiki TODO list_

**Comment by vzh** [comment]
@gareth8118 Thank you! One minor note though. There is no need to translate debug messages.
@peter-b Thank you for review and fixes!
