### ISSUE TITLE
Rename libgedacairo to libleptonrenderer

### ISSUE THREAD

**Issue by peter-b** [lepton-eda/lepton-eda#54]
Our `libgedacairo` actually uses the same _code_ as upstream geda-gaf at the moment, but when compiled it has a dependency on `liblepton` rather than `libgeda`. We should rename it to `libleptonrenderer` or `libleptoncairo` or something.

~~The current split between `libgedacairo` and `liblepton` seems a little arbitrary.  Maybe it would make sense to merge `libgedacairo` into `liblepton` rather than rename the library.  I can't see any immediate downside to this.~~

This blocks v1.9.3 because of the soname conflict with geda-gaf.

**Comment by ehennes775** [comment]
Sent from my iPhone

> On Feb 19, 2017, at 10:40 AM, Peter TB Brett <notifications@github.com> wrote:
> 
> Our libgedacairo actually uses the same code as upstream geda-gaf at the moment, but when compiled it has a dependency on liblepton rather than libgeda.
> 
> The current split between libgedacairo and liblepton seems a little arbitrary. Maybe it would make sense to merge libgedacairo into liblepton rather than rename the library. I can't see any immediate downside to this.
> 
It would be nice to have a GUI widget library. Maybe move the contents of libgedacairo into liblepton, rename libgedacairo to libleptongui or something, then move widgets from gschem into libleptongui.

**Comment by vzh** [comment]
@peter-b I would like to keep rendering library separate. Besides, it would be simpler to just rename it on this stage.
@ehennes775 I think having a gui widget library is a good idea. I wouldn't merge the cairo library with the gui library. Cairo funcs are used by non-gui tools, too.
