### ISSUE TITLE
Reorganize the context menu

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#545]
Although I do not use context menu in lepton-schematic and still believe
that the right mouse button should be used for mouse panning (#369, point 5),
it's time to update it with more relevant menu items.
Here's the screenshots of current context menu (on the left)
and possible replacement (on the right):

![context_menu](https://user-images.githubusercontent.com/26083750/72560209-a2d10780-38b7-11ea-980e-8be6fc49f758.png)

Any suggestions?

**Comment by vzh** [comment]
You don't like buses, as I can see :-)  I wouldn't throw them out.
Getting rid of zooming entries is OK with me (why are they there?).  I would remove `Select` as well.
Moving `Add component` to the top seems to be a good idea.

**Comment by graahnul-grom** [comment]
![ctx_menu_new_1](https://user-images.githubusercontent.com/26083750/72672944-c3de5780-3a73-11ea-992e-76878048faf8.png)

**Comment by vzh** [comment]
Yeah, this last version suits me well :-)
