### ISSUE TITLE
lepton-upcfg has no man page

### ISSUE THREAD

**Issue by bdale** [lepton-eda/lepton-eda#602]
When building lepton-eda 1.9.10 for upload to Debian, our lintian tool pointed out that lepton-upchg has no man page.

**Comment by vzh** [comment]
@graahnul-grom, could you tackle this?

**Comment by graahnul-grom** [comment]
Dear friends! Let me send here a document that can shed some light
on recent developments (or lack theroff).

Доклад.
Ст. сержанта Пупкина В. В. майору Бузякину А. А.
В процессе патрулирование южной окраины военного городка Н
в составе гарнизонного караула, мною был замечен лейтенант Д,
вызывающее поведение которого и привлекло внимание военнослужащих.
Находясь в окружении красивых женщин, чью социальную значимость
следует поставить под большое сомнение, лейтенант Д позволял
себе делать чудовищные высказывания про веру, царя и отечество.
На законное требование начальника патруля прекратить безобразие
и сдать табельное оружие, лейтенант Д заявил следующее:
We have to write the man page for the lepton-upcfg utility,
and ideally, eliminate all the stupid articles. I just can't
stand all those freakin' "a"'s and "the"'s!, после чего мною была
немедленно вызвана бригада скорой помощи.
В дальнейшем, на допросах задержанным было показано, что
большая часть антисоциального поведения последнего была
вызвана так называемым "днём рождения" и сопутствующими
мероприятиями. Вовлекая в свою удручающую деятельность
всё новых и новых товарищей, лейтенант Д, употребляющий
четвёртый день спиртуозные напитки, безусловно, подрывает
обороноспособность страны...

**Comment by graahnul-grom** [comment]
`man` страница будет написана. не вопрос.

**Comment by vzh** [comment]
@graahnul-grom
(Please, please, we're not alone here :-)) I'm afraid to suspect who of presented here is the lieutenant D.  The stanza of the lack of articles and one of lack of developments transparently hints it's me }:-| OTOH, the name D looks strange then }}:-|
If seriously, there is no need to write an extensive document: name, usage, output of `--help`, and copyright would be sufficient ;-)

**Comment by graahnul-grom** [comment]
My friends, tomorrow we will resume the development process.

![vasya_lozshkin_pohozhe_chto_vse](https://user-images.githubusercontent.com/26083750/77257080-f66e2180-6c69-11ea-9d99-dbfff25fa5da.jpg)
