### ISSUE TITLE
Cannot select a locked object

### ISSUE THREAD

**Issue by zo0om** [lepton-eda/lepton-eda#651]
Obviously you don't want to be able to edit it, but it's confusing for us newbies, so maybe it could produce a dialogue telling you it's locked, and possibly offering to unlock it? I suppose that should only happen if you click on an individual object rather than multi-selecting by dragging an area.

**Comment by graahnul-grom** [comment]
@zo0om Matthew, I hope the attached Guile script will help you to
work with locked objects, please test it.
It binds two keyboard shortcuts: `Ctrl+Shift+L` to select all locked
objects on the active page, and `Shift+L` to select each one in
succession - then, you can press `E Shift+L` to unlock the object
or `E E` to edit its attributes.
Keys are customizable, edit the shortcuts definitions in the
script (the first two lines of code).

![test-select-locked](https://user-images.githubusercontent.com/26083750/85226930-8dfa2200-b3c9-11ea-9cd1-b56c2879f5a2.png)

With the schematic above (attached) when you press `Ctrl+Shift+L`,
all locked components should become selected: R1, C1
and the title block. Pressing `Shift+L` several time should select
R1, then C1, then titleblock, then R1 again, etc.
You should also see messages in the log window:

![select-locked-log-wnd](https://user-images.githubusercontent.com/26083750/85227080-8a1acf80-b3ca-11ea-9424-e9bc6a229b8e.png)

Shortcuts:

![select-locked-hotkeys](https://user-images.githubusercontent.com/26083750/85227087-999a1880-b3ca-11ea-80ae-929e11c77046.png)

The script (`select-locked.scm`) can be loaded from the `gschemrc`
configuration file (e.g. `~/.config/lepton-eda/gschemrc`):

```scheme
( primitive-load "/path/to/select-locked.scm" )
```

[select-locked.tar.gz](https://github.com/lepton-eda/lepton-eda/files/4809614/select-locked.tar.gz)

**Comment by graahnul-grom** [comment]
I have improved the [script](https://graahnul-grom.github.io/scm/select-locked.scm.html), `Ctrl+L` now selects a locked component
under the mouse cursor.

[select-locked-improved.tar.gz](https://github.com/lepton-eda/lepton-eda/files/4814236/select-locked-improved.tar.gz)

**Comment by graahnul-grom** [comment]
Simplified and fixed [script](https://graahnul-grom.github.io/scm/select-locked.scm.html) [[download](https://graahnul-grom.github.io/scm/select-locked.scm)].
Correctly handle symbols with no graphical elements and
placeholders for missing symbols.
At the moment, placeholders for locked components can be
selected by cycling through them (`Shift+L`), but not by
pointing with the mouse (`Ctrl+L`).
Further improvement would be to determine the placeholder type
used (read it from config: `schematic.gui::small-placeholders`)
and calculate each placeholder's bounds, including them to the
list of locked objects tested against the mouse pointer position.

You do not need to modify script's code to change the
key bindings anymore. Set them the usual way by adding
the `global-set-key` expressions to your `gschemrc` file
(changing shortcuts as needed):

```scheme
( global-set-key "<Control><Shift>L" 'select-locked-all )
( global-set-key "<Shift>L"          'select-locked-next )
( global-set-key "<Control>L"        'select-locked-under-mouse )
```

@zo0om Could you please test it?
In case this script works for you (I hope), could you consider
it as a solution of the problem described in this issue?

[select-locked-improved-2.tar.gz](https://github.com/lepton-eda/lepton-eda/files/4820342/select-locked-improved-2.tar.gz)

**Comment by graahnul-grom** [comment]
Done. The [script](https://graahnul-grom.github.io/scm/select-locked.scm.html) [[download](https://graahnul-grom.github.io/scm/select-locked.scm)] determines the type of placeholders used and calculates their bounds.
Now placeholders for missing locked components under the mouse
cursor can be selected with `Ctrl+L`.

[select-locked-improved-3.tar.gz](https://github.com/lepton-eda/lepton-eda/files/4873325/select-locked-improved-3.tar.gz)

**Comment by graahnul-grom** [comment]
I've adapted my `select-locked` script [1] for `lepton-schematic`.
`Edit->Select Locked` menu item has been added; it cycles
selection through locked components on the current page,
printing log messages.
No other functions (there were 'select all locked' and
'select locked under mouse' - is it worth to retain them?).
Script itself has been converted to module `(schematic slck)`,
exporting `select-locked-next()` function.
The *action* is named `&edit-select-locked`.
Haven't assigned a key to it yet.

@vzh Could you please take a look at these changes [2]?


[1] github.com/graahnul-grom/graahnul-grom.github.io.git/scm/select-locked.scm
[2] https://github.com/graahnul-grom/lepton-eda/tree/tb_364_select_locked
