### ISSUE TITLE
Overscored signal names are unreadable in PDF

### ISSUE THREAD

**Issue by rundel-tech** [lepton-eda/lepton-eda#661]
I am using lepton-cli export to generate a PDF of my design. The command is:

lepton-cli export --format=pdf --paper=iso_a4 -o $out/Schematics.pdf *.sch

The resulting schematics look fine except that every signal with an overscore is replaced by a rectangle. A similar issue affects lepton-schematic, but there the height of the overscore is affected by the zoom level. This also affects labels in symbols.

`lepton-cli --version` reports the version as "Lepton EDA 1.9.10.20200319 (git: 56bb6e5)".

PDF schematics:

![Screenshot from 2020-06-29 17-59-48](https://user-images.githubusercontent.com/67599918/86034371-60008780-ba32-11ea-85e7-3e04de452e52.png)

lepton-schematic:

![Screenshot from 2020-06-29 18-07-58](https://user-images.githubusercontent.com/67599918/86035066-938fe180-ba33-11ea-8234-ac079c4e787e.png)

**Comment by vzh** [comment]
This has been fixed along with other issues in #622 and the last release, 1.9.11, includes the fixes and is recommended for use in distributions.

**Comment by rundel-tech** [comment]
That's good news. Thanks for the quick response.

**Comment by rundel-tech** [comment]
For the benefit of anyone else encountering this issue, the version in the Ubuntu repositories is currently 1.9.10-2. https://packages.debian.org/unstable/lepton-eda has 1.9.11-1 (lepton-eda_1.9.11-1_amd64.deb). Installing this fixed the issue.

**Comment by vzh** [comment]
Please also take a look at [this page](https://github.com/lepton-eda/lepton-eda/wiki/Ubuntu) :-)

**Comment by graahnul-grom** [comment]
@rundel-tech @vzh Could we close this issue?

**Comment by vzh** [comment]
I'm afraid if we close it just now, somebody will report it once again.
OTOH, the more issues we close, the better we work ;-)
