### ISSUE TITLE
Create Lepton Project at OpenHub

### ISSUE THREAD

**Issue by ehennes775** [lepton-eda/lepton-eda#72]
Create a project for lepton-eda at www.openhub.net. This website will allow us to track the metrics of the project.

**Comment by vzh** [comment]
@ehennes775 I think this is a great idea! Could you do this? :-)

**Comment by ehennes775** [comment]
I've created the initial project on OpenHub:
https://www.openhub.net/p/lepton-eda

@vzh Can you sign up for an account and set yourself up as the manager?

**Comment by vzh** [comment]
@ehennes775 I've registered myself as the manager. Thank you!
