### ISSUE TITLE
Organize the repository

### ISSUE THREAD

**Issue by graahnul-grom** [lepton-eda/lepton-eda#732]
Now that the dust has settled, we have time to look at the
repository layout. It's far from perfect. "Inconsistency"
is the keyword here.

Let me propose the following changes:

- Move `lepton-cli` source code into a hierarchy similar to
that of the other components: `cli/src/`, `cli/docs/`, etc.
**UPDATE:** fixed in #740

- Do not mix symbols with other stuff. Split up the contents
of the symbols directory, e.g.:
  symbols/
  |-- docs/
  |-- scheme/
  |-- sym/

**UPDATE:** fixed in #751

BTW, do we really need the `nc.doc` satiric document?
**UPDATE:** fixed in #761: moved to Lepton manual

- Remove the `docs/toplevel` directory with the only file
which contains the only link to the wiki main page.
**UPDATE:** fixed in #750

- Create `docs/news/` and move `NEWS-1.9.2.txt` there.
**UPDATE:** fixed in #734

- Move `libleptonattrib/design` to `docs/`.
**UPDATE:** fixed in #734

- Clean up the mess in `utils/`. All that utils/scripts
separation is obsolete. We do not have "utils" or "scripts",
we have the *components* of the suite, which are installed
into the system `bin/` and `lib/` directories.
Here they are, in no particular order:

1) `liblepton`
2) `libleptongui`
3) `libleptonattrib`
4) `schematic`
5) attrib  [**UPDATE:** => `utils/attrib` #763]
6) netlist  [**UPDATE:** => `utils/netlist` #742]
7) cli  [**UPDATE:** => `utils/cli` #740]
8) tragesym  [**UPDATE:** => `utils/tragesym` #738]
9) sch2pcb  [**UPDATE:** => `utils/sch2pcb` #735]
10) archive  [**UPDATE:** => `utils/archive` #739]
11) symcheck  [**UPDATE:** => `utils/symcheck` #739]
12) symfix  [**UPDATE:** => `utils/symfix` #739]
13) embed  [**UPDATE:** => `utils/embed` #739]
14) schdiff  [**UPDATE:** => `utils/schdiff` #739]
15) pcb_backannotate  [**UPDATE:** => `utils/pcb_backannotate` #739]
16) renum  [**UPDATE:** => `contrib/renum` #756]
17) refdes_renum  [**UPDATE:** => `utils/refdes_renum` #739]
18) upcfg  [**UPDATE:** => `utils/upcfg` #739]

Eighteen. Not 100, not 50. I believe each of the above
should live in its own directory, even if it's under
`utils/` (and we have to decide what we consider a "utility").

- Consider moving `lepton-renum` to `contrib/`. It does exactly
the same as `lepton-refdes_renum`, IIUC.
**UPDATE:** fixed in #756

- Rename all `geda-*` files under `m4/` to `lepton-*`.
**UPDATE:** fixed in #736

@vzh Perhaps, I missed something, but why parts of the `netlist`
and `symcheck` Scheme code are now in the `liblepton/scheme` subdir?

**Comment by vzh** [comment]
IMO, *utility* is a useful tool for solving of a particular issue, not main, usually CLI.

**Comment by vzh** [comment]
All Scheme modules can be used by many tools in the suite, e.g. `lepton-schematic` uses `lepton`, `netlist`, and `symcheck` modules.  That is why they are in the same directory.  It facilitates unit-testing as well.  I would move that directory to the root of the repository (as Guile itself has the `module/` directory). However, we also have so named `core` modules.  I would prefer to get rid of them first.

**Comment by vzh** [comment]
I second moving utils into own directories in `utils/` with all related docs, tests, examples, etc.

**Comment by vzh** [comment]
Too many problems in one issue.  I would prefer to see them in different issues.  Otherwise we never fix them :-)

**Comment by graahnul-grom** [comment]
> IMO, utility is a useful tool for solving of a particular issue, not main, usually CLI.

Agree. All things, but lepton-schematic, are utilities, then? :-)

> Too many problems in one issue.

Absolutely. What should we move to separate issues, WDYT?
And what could we already start working on?

**Comment by vzh** [comment]
> > IMO, utility is a useful tool for solving of a particular issue, not main, usually CLI.
> 
> Agree. All things, but lepton-schematic, are utilities, then? :-)

Well, yes, I believe :-)
 
> > Too many problems in one issue.
> 
> Absolutely. What should we move to separate issues, WDYT?

Almost any paragraph in your first message here starting with dot :-)

> And what could we already start working on?

**Comment by graahnul-grom** [comment]
[utils/README](https://github.com/lepton-eda/lepton-eda/blob/master/utils/README) mostly contains information about utilities in `contrib/`.
Other programs are documented in man pages, their authors are
also mentioned there.
Could we reduce this file to contain info only on utils in `contrib/`
and move it there?

**Comment by graahnul-grom** [comment]
There are other quite old/obsolete files, e.g.:
- `liblepton/HACKING`
- `libleptonattrib/NOTES`
- `libleptonattrib/ToDos`
- `libleptongui/TODO`
- `netlist/BUGS`

I would consider at least moving them to corresponding
`docs/` directories.

**Comment by graahnul-grom** [comment]
And I have serious doubts in usefulness of `ChangeLog`
files we generate during build (taking up space and time):

1) We maintain the `NEWS.md` file
2) All history is available in `git`
3) All history is available on `github.com` web site

**Comment by vzh** [comment]
> [utils/README](https://github.com/lepton-eda/lepton-eda/blob/master/utils/README) mostly contains information about utilities in `contrib/`.
> Other programs are documented in man pages, their authors are
> also mentioned there.
> Could we reduce this file to contain info only on utils in `contrib/`
> and move it there?

Yep, though a small README file with info on how to get better info on the utilities would not harm :-)  As well as sections in the manual for each utility.

**Comment by vzh** [comment]
> There are other quite old/obsolete files, e.g.:
> 
>     * `liblepton/HACKING`
> 
>     * `libleptonattrib/NOTES`
> 
>     * `libleptonattrib/ToDos`
> 
>     * `libleptongui/TODO`
> 
>     * `netlist/BUGS`
> 
> 
> I would consider at least moving them to corresponding
> `docs/` directories.

Please do. (It would be nice to revise them some day.)

**Comment by vzh** [comment]
> And I have serious doubts in usefulness of `ChangeLog`
> files we generate during build (taking up space and time):
> 
>     1. We maintain the `NEWS.md` file
> 
>     2. All history is available in `git`
> 
>     3. All history is available on `github.com` web site

If we drop ChangeLog creation  as Guile devs did in 2008 we have to add something like [this](http://git.savannah.gnu.org/cgit/guile.git/tree/ChangeLog).

Another way is to create one common ChangeLog in the root directory like [here](https://github.com/spk121/guile-gi/blob/master/Makefile.am).  Some people install tools from tarballs and expect to see the info there.

I would not mind if any of the options is implemented.

**Comment by graahnul-grom** [comment]
@vzh I think the single `ChangeLog` file in the root
directory with explanation that we no longer use
log files and referring users to `git` like in Guile
is the way to go.

> Some people install tools from tarballs and expect to see the info there.

Since #473 we install `NEWS.md`. IMHO, it's sufficient
for the end users. Developers/advanced users shouldn't have
any problems with git/github, I hope.

**Comment by vzh** [comment]
As I've already said, I'm OK with both approaches.

**Comment by graahnul-grom** [comment]
We put the `lepton-attrib` script to the same dir
as `libleptonattrib`, it doesn't look good.
Should be placed in its own `attrib` dir (like
`lepton-schematic`) or moved to `utils/`.
Or something else. WDYT?

**Comment by vzh** [comment]
I would move anything executable to `utils/` :-)

**Comment by graahnul-grom** [comment]
Please, let's not move `lepton-schematic` to `utils/`,
at least for now! It is *not* a utility and will be looking odd there.

**Comment by graahnul-grom** [comment]
What do you think about `symbols/docs/nc.doc`?
Frankly, it looks like a joke.
Could we move/remove or at least do not build and install it?

**Comment by vzh** [comment]
Probably move its contents to manual?  Just to make it not so boring :-)

**Comment by graahnul-grom** [comment]
:-) It would be nice!

**Comment by vzh** [comment]
OK, I'll try to do it then.

**Comment by vzh** [comment]
@graahnul-grom, is anything else we should do to close this issue?

**Comment by graahnul-grom** [comment]
IIRC, we thought about moving common Scheme files (now
piled up in `liblepton`) to a separate top-level directory.

And a couple of (minor) points:
- To stay consistent, we should rename the `gettext` domain
for `libleptongui` in `libleptongui/po/Makevars` and
elsewhere: it's still called `lepton-schematic`.
- It won't hurt to revise `.gitignore` files: many of them
could be removed and/or bring up to date.

**Comment by vzh** [comment]
As for toplevel directory for Scheme files, it was just an idea.  I would prefer to not do it now.  Let's do it when we get rid of C `core` modules.  I'm working on this now and having some progress.  Not sure, though, when it will be complete.

Two other (minor) issues can be solved just now, if someone would want to work on them, or, as an option, we could delay them by making up a couple of new issues.  It's just not so very convenient to orient yourself in the mass of comments and done stuff here.

WDYT?

**Comment by graahnul-grom** [comment]
You are right about the `core` modules, let's get rid of them first.
IMHO, gettext/gitignore stuff is not worth opening new issues,
and certainly won't keep us from closing this one.
Our repository now looks *much* better, thank you!

I'm closing #732 "Organize the repository".

**Comment by vzh** [comment]
Thank you!
