### ISSUE TITLE
Add basic attributes to basic symbols

### ISSUE THREAD

**Issue by vzh** [lepton-eda/lepton-eda#784]
Add `value` and `footprint` attributes to basic symbols.
There are basic symbols in `sym/analog/`; new user most likely start
their work with lepton by using them. The only attribute they have
(most of them) is `refdes`. What's the use for symbol which has
neither `value` nor `footprint` attribute? I propose to add these
attributes without bumping symversion.

by @graahnul-grom, moved here from #369

**Comment by graahnul-grom** [comment]
@vzh, thank you! :)
