### ISSUE TITLE
Wrong attribute position when the user chooses Add->Attribute from menu 

### ISSUE THREAD

**Issue by vzh** [lepton-eda/lepton-eda#788]
I tried to trigger the action by clicking on the menu item instead of using its shortcut.  The action finished, the schematic got changed but the contents looks like this:
```
v 20201211 2
T -1211907324 -1121995728 8 10 1 0 0 0 1
netname=qqq
```
which is obviously wrong.

In case, when the pointer position is out of the canvas, some reasonable default should be used for attribute position, say, the center of the page view, or a new attribute could go to the page selection list instead in order to let the user place it then.

**Comment by graahnul-grom** [comment]
Yes, I can reproduce it.
But it happens only with *empty* schematics
(i.e. no title block or other objects).
Otherwise, a new attribute is placed
at the lower-left corner.
